import React from 'react'

export default function Home() {
  return (
    <div className='flex flex-col gap-10 px-10 py-5'>
      <p>
        Test Home Page
      </p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus cum doloremque consequuntur cumque, at labore animi, saepe esse illo odio provident repudiandae temporibus minima nam praesentium vitae commodi nemo delectus eum nihil? Suscipit expedita earum harum inventore provident ut, dignissimos illo nobis molestiae amet rem corrupti saepe, quos dolores maxime corporis delectus sit. Aut, error commodi! Officia eos nihil error rerum a fugit at illum! Recusandae accusantium nobis fuga quod totam voluptatibus veniam vero nam molestiae soluta dolore voluptas veritatis amet animi iure non, odio expedita error repellat maxime pariatur laboriosam. Optio ratione pariatur molestiae minima cupiditate nisi soluta alias?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus cum doloremque consequuntur cumque, at labore animi, saepe esse illo odio provident repudiandae temporibus minima nam praesentium vitae commodi nemo delectus eum nihil? Suscipit expedita earum harum inventore provident ut, dignissimos illo nobis molestiae amet rem corrupti saepe, quos dolores maxime corporis delectus sit. Aut, error commodi! Officia eos nihil error rerum a fugit at illum! Recusandae accusantium nobis fuga quod totam voluptatibus veniam vero nam molestiae soluta dolore voluptas veritatis amet animi iure non, odio expedita error repellat maxime pariatur laboriosam. Optio ratione pariatur molestiae minima cupiditate nisi soluta alias?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus cum doloremque consequuntur cumque, at labore animi, saepe esse illo odio provident repudiandae temporibus minima nam praesentium vitae commodi nemo delectus eum nihil? Suscipit expedita earum harum inventore provident ut, dignissimos illo nobis molestiae amet rem corrupti saepe, quos dolores maxime corporis delectus sit. Aut, error commodi! Officia eos nihil error rerum a fugit at illum! Recusandae accusantium nobis fuga quod totam voluptatibus veniam vero nam molestiae soluta dolore voluptas veritatis amet animi iure non, odio expedita error repellat maxime pariatur laboriosam. Optio ratione pariatur molestiae minima cupiditate nisi soluta alias?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus cum doloremque consequuntur cumque, at labore animi, saepe esse illo odio provident repudiandae temporibus minima nam praesentium vitae commodi nemo delectus eum nihil? Suscipit expedita earum harum inventore provident ut, dignissimos illo nobis molestiae amet rem corrupti saepe, quos dolores maxime corporis delectus sit. Aut, error commodi! Officia eos nihil error rerum a fugit at illum! Recusandae accusantium nobis fuga quod totam voluptatibus veniam vero nam molestiae soluta dolore voluptas veritatis amet animi iure non, odio expedita error repellat maxime pariatur laboriosam. Optio ratione pariatur molestiae minima cupiditate nisi soluta alias?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus cum doloremque consequuntur cumque, at labore animi, saepe esse illo odio provident repudiandae temporibus minima nam praesentium vitae commodi nemo delectus eum nihil? Suscipit expedita earum harum inventore provident ut, dignissimos illo nobis molestiae amet rem corrupti saepe, quos dolores maxime corporis delectus sit. Aut, error commodi! Officia eos nihil error rerum a fugit at illum! Recusandae accusantium nobis fuga quod totam voluptatibus veniam vero nam molestiae soluta dolore voluptas veritatis amet animi iure non, odio expedita error repellat maxime pariatur laboriosam. Optio ratione pariatur molestiae minima cupiditate nisi soluta alias?</p>
      </div>
  )
}
